version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build: ./server/
    ports:
      - "4001:4001"
    volumes:
      - ./server:/usr/src/server
    depends_on:
      - mongodb
  frontend:
    build: ./client/
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/client
    depends_on:
      - backend